[project]
name = 'Tokenized-Commercial-Real-Estate-Maintenance-Fund'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fund-contribution]
path = 'contracts/fund-contribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-registration]
path = 'contracts/property-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
